
services:
    nginx:
        build: nginx
        ports:
          - 8000:80
        depends_on:
          - api1
          - api2
    api1:
        build: API
    api2:
        build: API
    db:
        build: db


    prometheus-nginx-exporter:
      image: nginx/nginx-prometheus-exporter
      ports:
        - 9113:9113
      environment:
        - SCRAPE_URI=http://nginx/metrics
      depends_on:
        - nginx
    prometheus:
        build: Prometheus
        environment:
          - PORT=8080
        ports:
          - 9090:9090
    grafana:
        image: grafana/grafana
        ports:
          - 3000:3000
        depends_on:
          - prometheus

