
services:
    psql:
        build: psql
        user: postgres
        healthcheck:
          test: ["CMD-SHELL", "pg_isready"]
          interval: 10s
          timeout: 5s
          retries: 5


    api1:
        build: API
#        ports:
#          - 8080:8000
        depends_on:
          psql:
            condition: service_healthy
        environment:
          PSQL_ADDRESS: "psql"


    api2:
        build: API
        depends_on:
          psql:
            condition: service_healthy
        environment:
          PSQL_ADDRESS: psql

    nginx:
        build: nginx
        ports:
          - 8000:80
        depends_on:
          - api1
          - api2



    nginx-exporter:
      image: nginx/nginx-prometheus-exporter
      ports:
        - 9113:9113
      environment:
        - SCRAPE_URI=http://nginx/metrics
      depends_on:
        - nginx

    psql-exporter:
      image: wrouesnel/postgres_exporter
      environment:
        DATA_SOURCE_NAME: "postgresql://postgres:postgres@psql:5432/postgres?sslmode=disable"
      ports:
        - 9187:9187


    prometheus:
        build: Prometheus
        ports:
          - 9090:9090
    grafana:
        image: grafana/grafana
        ports:
          - 3000:3000
        depends_on:
          - prometheus

