global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s

rule_files:
  - "rules.yml"

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - localhost:9090

- job_name: grafana
  static_configs:
    - targets:
        - localhost:3000

- job_name: api
  static_configs:
  - targets:
    - api-service.default:9001


- job_name: nginx-exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - nginx-service.default:9113

- job_name: psql-exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - psql-service.default:9187