global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s

alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
        - localhost:9093

rule_files:
  - "rules.yml"

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - prometheus:9090

- job_name: grafana
  static_configs:
    - targets:
        - grafana:3000

- job_name: api
  static_configs:
  - targets:
    - api:9001

