global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s

rule_files:
  - "rules.yml"

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - prometheus:9090

- job_name: grafana
  static_configs:
    - targets:
        - grafana:3000

- job_name: api1
  static_configs:
  - targets:
    - api1:9001

- job_name: api2
  static_configs:
  - targets:
    - api2:9001

- job_name: nginx-exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - prometheus-nginx-exporter:9113
