groups:

  - name: Latency
    rules:
      - record: job:app_response_latency_seconds:rate1m
        expr: rate(slow_request_latency_seconds_sum[1m]) / rate (slow_request_latency_seconds_count[1m])
#        annotations:
#          summary: 'API latency'
#          description: 'API latency for endpoint "/expensive"'

      - alert: AppLatencyAbove5sec
        expr: job:app_response_latency_seconds:rate1m >= 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: 'API latency over 5 secs'
          description: 'App latency of instance {{ $labels.instance }} of job {{ $labels.job }} is {{ $value }} for more than 5min'

  - name: Exceptions
    rules:
    - alert: ExceptionOccured
      expr: app_exception_count_total > 0
      labels:
        severity: critical
      annotations:
          summary: 'Uncaught exception occured'
          description: 'An uncaught exception occured in {{ $labels.endpoint }} on endpoint {{ $labels.endpoint }}'



