
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
    - name: nginx-proxy
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: prometheus-export
      protocol: TCP
      port: 9001
      targetPort: 9001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-app
          image: juliendosiere/deploy.api:latest
          imagePullPolicy: Always
          env:
            - name: PSQL_ADDRESS
              value: "psql-service.default"
