

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: nginx-app
      protocol: TCP
      port: 8000
      targetPort: 80
    - name: nginx-exporter
      protocol: TCP
      port: 9113
      targetPort: 9113


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-app
          image: juliendosiere/deploy.nginx:latest
          imagePullPolicy: Always
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter
          env:
          - name: SCRAPE_URI
            value: http://localhost/metrics


