

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  type: LoadBalancer
  ports:
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus-app
          image: juliendosiere/deploy.prometheus:latest
          imagePullPolicy: Always
        - name: grafana-app
          image: grafana/grafana


