
apiVersion: v1
kind: Service
metadata:
  name: psql-service
spec:
  selector:
    app: psql
  type: ClusterIP 
  ports:
    - name: psql-app
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: psql-exporter
      protocol: TCP
      port: 9187
      targetPort: 9187

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
        - name: psql-app
          image: juliendosiere/deploy.psql:latest
          imagePullPolicy: Always
        - name : psql-exporter
          image: wrouesnel/postgres_exporter
          env:
          - name: DATA_SOURCE_NAME
            value: postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable

